### ISSUE TITLE
Move build artifacts out of build branch and into github releases

### ISSUE THREAD

**Issue by jab416171** [DenysAshikhin/gameplay-planner#15]
You can create a tag and then create a release here: https://github.com/DenysAshikhin/gameplay-planner/releases/new
After that you can upload the artifacts for that release, and then pull them down on the build server with curl or wget.

**Comment by DenysAshikhin** [comment]
I removed the build branch and the build should be ignored now. Mainly because it got too big for the repo anyway so kinda solves this issue?
