### ISSUE TITLE
Farming Page - Fry Graph 

### ISSUE THREAD

**Issue by MeLovesCheese** [DenysAshikhin/gameplay-planner#25]
Picture 1 - upload data, go to farming page, change hours to something random eg 8, everything working as expected
![image](https://github.com/DenysAshikhin/gameplay-planner/assets/50808888/6b036f4d-213b-4b9f-a630-08bb95d80fac)

Picture 2 - clicked calculate afk, graph doesn't appear, clicking log and linear does not fix 
![image](https://github.com/DenysAshikhin/gameplay-planner/assets/50808888/b992bfb0-3975-4b42-9859-8e68cbec3729)

Picture 3 - exact same thing happens on the step calculator
![image](https://github.com/DenysAshikhin/gameplay-planner/assets/50808888/dada791b-93e4-48b4-ab01-bba2a0f867d5)

I think it was working correctly before I had over 1e360 fries

**Comment by DenysAshikhin** [comment]
Should be resolved now
