### ISSUE TITLE
Reserve reincarnation points to enable trading

### ISSUE THREAD

**Issue by asvanberg** [DenysAshikhin/gameplay-planner#35]
Once the trade center reaches level 10 you get the ability to trade with reincarnation points (RP). The infinity corner page on the planner shows the recommended purchases based on how many RP you have available. If you buy everything it recommends you will not have any RP left to do trades with.

Add a way to reserve `N` trades worth of RP before calculating the suggested purchases such that after buying all the recommendations you can still afford to do `N` trades costing RP.

**Comment by DenysAshikhin** [comment]
Done, let me know if there are any issues!
