### ISSUE TITLE
Missing horizontal scrollbars

### ISSUE THREAD

**Issue by Power46-GitHub** [DenysAshikhin/gameplay-planner#38]
There are no horizontal scrollbars to go left and right in the Outposts and Contagion Tabs. Having horizontal scrollbars would be useful for cases like mine where I have the planner on a left or right half of a secondary monitor. I mentioned this on the thread on Discord and you said to send it in a GitHub issue.

**Comment by DenysAshikhin** [comment]
Done, let me know if there are any issues!
