### ISSUE TITLE
Reserve Average Trade costs

### ISSUE THREAD

**Issue by GCoast** [DenysAshikhin/gameplay-planner#41]
Add a numeric input box so the user could select for how many average trade costs the resources should be reserved. This would be applicable for Protein and RP.

P.S. there was already a suggestion in Discord to add "Reserve Average Protein Trade Cost" checkbox into protein page. If the above would not be  implemented, than at least a checkbox on the protein  page would be nice

**Comment by DenysAshikhin** [comment]
Added, let me know if there any issues!
