### ISSUE TITLE
Miner card (exp and power) not matching in game 

### ISSUE THREAD

**Issue by DenysAshikhin** [DenysAshikhin/gameplay-planner#5]
![image](https://github.com/DenysAshikhin/gameplay-planner/assets/10791321/2abcbada-419b-48e8-851d-398af180c40c)
vs
![image](https://github.com/DenysAshikhin/gameplay-planner/assets/10791321/55b58b0c-73c1-464d-97b8-d552af293574)

**Comment by MeLovesCheese** [comment]
Grasshopper card is also the same

**Comment by DenysAshikhin** [comment]
fixed
