### ISSUE TITLE
Pet team builder not abiding `use expedition` for manual pet selection

### ISSUE THREAD

**Issue by DenysAshikhin** [DenysAshikhin/gameplay-planner#7]
Essentially if you have `Use expedition pets` toggled on, the `Manual Pet Selection` does not actually respect that and only lets you filter pets you have unlocked:

![image](https://github.com/DenysAshikhin/gameplay-planner/assets/10791321/8b2ed01c-81e1-44c3-9224-937105809396)

**Comment by paulKra** [comment]
Question is whether it should concern pets in expeditions in the save file vs the ones from the page?

**Comment by DenysAshikhin** [comment]
In this case, pets in save file are already considered. The issue is that star flower is in because I had him enabled on the expedition page (and checked use expedition option), but because I don't actually own him it's not showing up in the list for whitelisting or blacklisting

**Comment by DenysAshikhin** [comment]
fixed
