### ISSUE TITLE
Add a timer icon for each step in step calc to quickly add it to the timer

### ISSUE THREAD

**Issue by DenysAshikhin** [DenysAshikhin/gameplay-planner#8]
Essentially where the pink spots are, would go a simple icon to quickly add the recommended step time to the `Timer` section.

![image](https://github.com/DenysAshikhin/gameplay-planner/assets/10791321/bd64d45e-0bfd-4af8-b3f9-bd81164d12e1)

**Comment by paulKra** [comment]
I'll start with that
