### ISSUE TITLE
Residue page  green text is sometimes factoring in future purchases

### ISSUE THREAD

**Issue by DenysAshikhin** [DenysAshikhin/gameplay-planner#9]
See screenshot:
![image](https://github.com/DenysAshikhin/gameplay-planner/assets/10791321/435d9a06-ce97-4e3b-86c9-57153a47d8d0)

I have a save file for reference if needed

**Comment by paulKra** [comment]
i have one now too, will take a look as to why that happpens.

**Comment by DenysAshikhin** [comment]
Seems to be resolved now, since one the updates, haven't heard anyone complain about it in a while. Will close in a week if no other issues for this pops up.
